version: '3.8'

services:
  mongo1:
    image: mongo:5
    container_name: prod-mongo1
    command: mongod --replSet myReplicaSet --bind_ip_all
    ports:
      - "37017:27017"
    volumes:
      - prod-mongo1-data:/data/db
    networks:
      - prod-mongoCluster

  mongo2:
    image: mongo:5
    container_name: prod-mongo2
    command: mongod --replSet myReplicaSet --bind_ip_all
    ports:
      - "37018:27017"
    volumes:
      - prod-mongo2-data:/data/db
    networks:
      - prod-mongoCluster

  mongo3:
    image: mongo:5
    container_name: prod-mongo3
    command: mongod --replSet myReplicaSet --bind_ip_all
    ports:
      - "37019:27017"
    volumes:
      - prod-mongo3-data:/data/db
    networks:
      - prod-mongoCluster

  mongo-init:
    image: ${INIT_REPLICA_IMG_NAME}
    container_name: prod-mongo-init
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: ["/wait-for-mongo.sh", "mongo1:27017", "/init-replica.sh"]
    networks:
      - prod-mongoCluster

  yolo5:
    image: ${YOLO5_IMG_NAME}
    container_name: prod-yolo5
    environment:
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    ports:
      - "9081:8081"
    networks:
      - prod-mongoCluster

  polybot:
    image: ${POLYBOT_IMG_NAME}
    container_name: prod-polybot
    environment:
      - TELEGRAM_APP_URL=${TELEGRAM_APP_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - YOLO5_URL=${YOLO5_URL}
    volumes:
      - /home/ubuntu/certs:/home/ubuntu
    ports:
      - "9443:8443"
    networks:
      - prod-mongoCluster
    secrets:
      - telegram_bot_token

networks:
  prod-mongoCluster:
    driver: bridge

volumes:
  prod-mongo1-data:
    driver: local
  prod-mongo2-data:
    driver: local
  prod-mongo3-data:
    driver: local

secrets:
  telegram_dev_token:
    file: ./telegram_bot_token.secret
