name: Polybot Service Deployment Prod

on:
  push:
    branches:
      - main

env:
  BOT_INSTANCE_DOMAIN: https://prod-bot.abedawaisy.click:8443

jobs:
  PolybotBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          cd polybot

          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/polybot:${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  Yolo5Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Print DockerHub Username (Debugging)
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          cd yolo5
   
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/yolo5:${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  ReplicaBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          cd init-replica
   
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/replica:${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  Deploy:
    name: Deploy Docker compose project
    runs-on: ubuntu-latest
    needs:
      - PolybotBuild
      - Yolo5Build
      - ReplicaBuild

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Copy Compose files to the EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.BOT_INSTANCE_DOMAIN }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: docker-compose-prod.yaml
          target: compose-yolo-polybot/prod/

      - name: Update the Docker Compose project in the EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.BOT_INSTANCE_DOMAIN }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd compose-yolo-polybot/prod/
            
            # Save telegram bot token in a secret file, to be used in docker-compose.yaml
            echo -n "${{ secrets.TELEGRAM_BOT_TOKEN_PROD }}" > telegram_bot_token.secret
            
            # Generate .env file
            cat <<EOF > .env
            POLYBOT_IMG_NAME=${{ secrets.DOCKERHUB_USERNAME }}/polybot:${{ github.run_number }}
            YOLO5_IMG_NAME=${{ secrets.DOCKERHUB_USERNAME }}/yolo5:${{ github.run_number }}
            INIT_REPLICA_IMG_NAME=${{ secrets.DOCKERHUB_USERNAME }}/replica:${{ github.run_number }}
            TELEGRAM_APP_URL=$BOT_INSTANCE_DOMAIN
            YOLO5_URL=http://yolo5:8081
            S3_BUCKET_NAME=abed-prediction-bucket
            EOF
            
            # Take the service down
            docker compose -f docker-compose-prod.yaml down
            
            # Take it up with the current updated values
            docker compose -f docker-compose-prod.yaml up -d
            
